/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Order;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-01-21T11:51:13.410Z[GMT]")
@Api(value = "orderDetails", description = "the orderDetails API")
public interface OrderDetailsApi {

    @ApiOperation(value = "", nickname = "orderDetailsOrderIdGet", notes = "Obtain information about specific product.", response = Order.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = Order.class) })
    @RequestMapping(value = "/orderDetails/{OrderId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Order> orderDetailsOrderIdGet(@ApiParam(value = "",required=true) @PathVariable("OrderId") Integer orderId);


    @ApiOperation(value = "", nickname = "orderDetailsUserNameGet", notes = "Obtain information about specific product.", response = Order.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = Order.class) })
    @RequestMapping(value = "/orderDetails/{UserName}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Order> orderDetailsUserNameGet(@ApiParam(value = "",required=true) @PathVariable("UserName") String userName);

}
